<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>distributed.event.platform</groupId>
    <artifactId>distributed-event-platform</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <!-- ✅ Centralized properties -->
    <properties>
        <java.version>17</java.version>
        <spring.boot.version>3.5.11</spring.boot.version>
    </properties>

    <!-- ✅ Modules -->
    <modules>
        <module>api-service</module>
        <!-- <module>ingestion-service</module>
        <module>processing-service</module>
        <module>persistence-service</module>
        <module>notification-service</module>c-->
        <module>common-lib</module> 
    </modules>

    <!-- ✅ Spring Boot BOM -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <!-- ✅ Centralized plugin management -->
    <build>
        <pluginManagement>
            <plugins>

                <!-- Compiler -->
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                    </configuration>
                </plugin>

                <!-- Spring Boot plugin -->
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring.boot.version}</version>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>

</project>